name: Wild WestSide
favicon: null
layout_spectrum: 0.00189
typography_spectrum: 0.2643676660954952
title: Faux Urban Taxidermy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.0625
  lightness: 0.2190179219469428
  saturation: 0.4977075862698257
  rhythmicContrast: 0.72071164380759
purpose: []
